import type { Metadata } from 'next';
import { Geist_Mono, Public_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';

const publicSans = Public_Sans({
  variable: '--font-public-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="h-full">
        <SidebarProvider className="h-full min-h-0 bg-white">
          <Navbar />
          <SidebarInset className="h-full min-h-0">
            <main className="h-full w-full overflow-auto">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
